### ISSUE TITLE
incidens

### ISSUE THREAD

**Issue by JuanDavidAvilaRaveloCampus** [JuanDavidAvilaRaveloCampus/Prueba#1]
asdf

**Comment by DavidPineda02** [comment]
Hola
![logo](https://github.com/JuanDavidAvilaRaveloCampus/Prueba/assets/128647493/03838659-1937-45a0-a330-92e09b95a382)

**Comment by JuanDavidAvilaRaveloCampus** [comment]
Gracias, @DavidPineda02 La respuesta es exactamente lo que estaba buscando
