### ISSUE TITLE
segundo

### ISSUE THREAD

**Issue by JuanDavidAvilaRaveloCampus** [JuanDavidAvilaRaveloCampus/Prueba#2]
eflkasdjf

**Comment by DavidPineda02** [comment]
Tercero
:D
![logo](https://github.com/JuanDavidAvilaRaveloCampus/Prueba/assets/128647493/03838659-1937-45a0-a330-92e09b95a382)

**Comment by JuanDavidAvilaRaveloCampus** [comment]
gracias @DavidPineda02 esa era :dagger:

**Comment by JuanDavidAvilaRaveloCampus** [comment]
Gracias @DavidPineda02 por tu colaboración, era lo que necesitaba
