### ISSUE TITLE
otra vez

### ISSUE THREAD

**Issue by JuanDavidAvilaRaveloCampus** [JuanDavidAvilaRaveloCampus/Prueba#3]
el mismo

**Comment by DavidPineda02** [comment]
xd
![logo](https://github.com/JuanDavidAvilaRaveloCampus/Prueba/assets/128647493/3f568c15-4883-462d-958b-9d2d4763de37)
@JuanDavidAvilaRaveloCampus

**Comment by JuanDavidAvilaRaveloCampus** [comment]
¡Gracias! La respuesta de @DavidPineda02 me ayudó mucho.
